#!/usr/bin/env bash

# This script installs the Chaotic-AUR repository.
# Based on: <https://aur.chaotic.cx/>.

echo "Checking if Chaotic-AUR is already enabled..."
if grep -F "[chaotic-aur]" /etc/pacman.conf > /dev/null; then
	echo "The repository is enabled."
	exit
fi

echo "Installing the Chaotic-AUR repository..."

# Check root permissions.
if [[ "${EUID}" -ne 0 ]]; then
	echo "Please run as root."
	exit 1
fi

echo "Installing Chaoutic-AUR primary key..."
pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com
pacman-key --lsign-key 3056513887B78AEB

echo "Installing Chaoutic-AUR keyring..."
pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' --noconfirm

echo "Installing Chaoutic-AUR mirrorlist..."
pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst' --noconfirm

echo "Enabling the Chaotic-AUR repository..."
cat << EOF >> /etc/pacman.conf
[chaotic-aur]
Include = /etc/pacman.d/chaotic-mirrorlist
EOF

echo "Installation of Chaotic-AUR completed."

